<h1>Gestionar Productos</h1>
<?php
require_once('./models/utiles/mensajesEmergentes.php');
mensajesEmergentes::borrar();
mensajesEmergentes::editar();

?>
<table border='1'>
  <tr>
    <th>ID</th>
    <th>Nombre</th>
    <th>Precio</th>
    <th>Stock</th>
    <th></th>
    <th><a href='index.php?controller=Productos&action=registrar' style='text-decoration: none'>+Crear+</a></th>
  </tr>

  <?php
  //<link rel="stylesheet" href="assets/css/styles.css" />
  if ($datos) {
    foreach ($datos as $c) {
      $id = $c['id'];
      $n = $c['nombre'];
      $p = $c['precio'];
      $s = $c['stock'];
      $borrar = "<a href='index.php?controller=Productos&action=borrar&id=$id' style='text-decoration: none'>Borrar</a>";
      $editar = "<a href='index.php?controller=Productos&action=editar&id=$id' style='text-decoration: none'>Editar</a>";
      echo "
  
    <tr>
      <td>$id</td>
      <td>$n</td>
      <td>$p$</td>
      <td>$s</td>
      <td>$borrar</td>
      <td>$editar</td>
    </tr>";
    }
  } else {
    echo "Sin productos en la base de datos";
  }

  ?>

</table>