<h1>Nuestros Productos</h1>
					<?php 
					foreach($productosRandom as $productos){
						$id = $productos['id'];
						$n = $productos['nombre'];
						$p = $productos['precio'];
						$img = $productos['imagen'];
						$url_imagen = "/Proyectos/Tienda/assets/img/".$img;
						$url_info = "?controller=Productos&action=info&producto=$id";
						$redireccion = "<a href='$url_info'><img src='$url_imagen'/></a>";
						$carrito = "href='?controller=Carrito&action=agregar&producto=$id'";
						echo "
					<div class='product'>
						$redireccion
						<h2>$n</h2>
						<p>$p euros</p>
						<a $carrito class='button'>Comprar</a>
					</div>";
					}
					
					?>
					<div class="product">
						<img src="assets/img/camiseta.png" />
						<h2>Camiseta Azul Ancha</h2>
						<p>30 euros</p>
						<a href="" class="button">Comprar</a>
					</div>

					<div class="product">
						<img src="assets/img/camiseta.png" />
						<h2>Camiseta Azul Ancha</h2>
						<p>30 euros</p>
						<a href="" class="button">Comprar</a>
					</div>

					<div class="product">
						<img src="assets/img/camiseta.png" />
						<h2>Camiseta Azul Ancha</h2>
						<p>30 euros</p>
						<a class="button">Comprar</a>
					</div>

				</div>